import type * as Monaco from 'monaco-editor';

export interface EditorTheme {
  id: string;
  label: string;
  color: string; // accent color for the swatch
  definition: Monaco.editor.IStandaloneThemeData;
}

export const editorThemes: EditorTheme[] = [
  {
    id: 'nvn-dark',
    label: 'Midnight',
    color: '#6366f1',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword.sql',    foreground: '818CF8', fontStyle: 'bold' },
        { token: 'keyword',        foreground: '818CF8', fontStyle: 'bold' },
        { token: 'string.sql',     foreground: '86EFAC' },
        { token: 'string',         foreground: '86EFAC' },
        { token: 'number',         foreground: 'FDA4AF' },
        { token: 'comment',        foreground: '475569', fontStyle: 'italic' },
        { token: 'identifier',     foreground: 'E2E8F0' },
        { token: 'operator',       foreground: '67E8F9' },
        { token: 'delimiter',      foreground: '94A3B8' },
        { token: 'type',           foreground: '67E8F9' },
        { token: 'predefined',     foreground: 'C084FC' },
      ],
      colors: {
        'editor.background':              '#0D1117',
        'editor.foreground':              '#E2E8F0',
        'editorLineNumber.foreground':    '#334155',
        'editorLineNumber.activeForeground': '#818CF8',
        'editor.selectionBackground':     '#312E8180',
        'editor.lineHighlightBackground': '#1E293B60',
        'editorCursor.foreground':        '#818CF8',
        'editor.inactiveSelectionBackground': '#1E293B',
      },
    },
  },
  {
    id: 'dracula',
    label: 'Dracula',
    color: '#BD93F9',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: 'FF79C6', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: 'FF79C6', fontStyle: 'bold' },
        { token: 'string',     foreground: 'F1FA8C' },
        { token: 'string.sql', foreground: 'F1FA8C' },
        { token: 'number',     foreground: 'BD93F9' },
        { token: 'comment',    foreground: '6272A4', fontStyle: 'italic' },
        { token: 'identifier', foreground: 'F8F8F2' },
        { token: 'operator',   foreground: 'FF79C6' },
        { token: 'delimiter',  foreground: 'F8F8F2' },
        { token: 'type',       foreground: '8BE9FD' },
        { token: 'predefined', foreground: '50FA7B' },
      ],
      colors: {
        'editor.background':              '#282A36',
        'editor.foreground':              '#F8F8F2',
        'editorLineNumber.foreground':    '#6272A4',
        'editorLineNumber.activeForeground': '#FF79C6',
        'editor.selectionBackground':     '#44475A',
        'editor.lineHighlightBackground': '#44475A50',
        'editorCursor.foreground':        '#F8F8F2',
        'editor.inactiveSelectionBackground': '#44475A50',
      },
    },
  },
  {
    id: 'monokai',
    label: 'Monokai',
    color: '#A6E22E',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: 'F92672', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: 'F92672', fontStyle: 'bold' },
        { token: 'string',     foreground: 'E6DB74' },
        { token: 'string.sql', foreground: 'E6DB74' },
        { token: 'number',     foreground: 'AE81FF' },
        { token: 'comment',    foreground: '75715E', fontStyle: 'italic' },
        { token: 'identifier', foreground: 'F8F8F2' },
        { token: 'operator',   foreground: 'F92672' },
        { token: 'delimiter',  foreground: 'F8F8F2' },
        { token: 'type',       foreground: '66D9E8' },
        { token: 'predefined', foreground: 'A6E22E' },
      ],
      colors: {
        'editor.background':              '#272822',
        'editor.foreground':              '#F8F8F2',
        'editorLineNumber.foreground':    '#75715E',
        'editorLineNumber.activeForeground': '#A6E22E',
        'editor.selectionBackground':     '#49483E',
        'editor.lineHighlightBackground': '#3E3D3250',
        'editorCursor.foreground':        '#F8F8F2',
        'editor.inactiveSelectionBackground': '#49483E50',
      },
    },
  },
  {
    id: 'night-owl',
    label: 'Night Owl',
    color: '#7FDBCA',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: 'C792EA', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: 'C792EA', fontStyle: 'bold' },
        { token: 'string',     foreground: 'ECC48D' },
        { token: 'string.sql', foreground: 'ECC48D' },
        { token: 'number',     foreground: 'F78C6C' },
        { token: 'comment',    foreground: '637777', fontStyle: 'italic' },
        { token: 'identifier', foreground: 'D6DEEB' },
        { token: 'operator',   foreground: '7FDBCA' },
        { token: 'delimiter',  foreground: 'D6DEEB' },
        { token: 'type',       foreground: 'ADDB67' },
        { token: 'predefined', foreground: '82AAFF' },
      ],
      colors: {
        'editor.background':              '#011627',
        'editor.foreground':              '#D6DEEB',
        'editorLineNumber.foreground':    '#4B6479',
        'editorLineNumber.activeForeground': '#7FDBCA',
        'editor.selectionBackground':     '#1D3B5380',
        'editor.lineHighlightBackground': '#0E2A3A60',
        'editorCursor.foreground':        '#80A4C2',
        'editor.inactiveSelectionBackground': '#1D3B5340',
      },
    },
  },
  {
    id: 'tokyo-night',
    label: 'Tokyo Night',
    color: '#7AA2F7',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: 'BB9AF7', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: 'BB9AF7', fontStyle: 'bold' },
        { token: 'string',     foreground: '9ECE6A' },
        { token: 'string.sql', foreground: '9ECE6A' },
        { token: 'number',     foreground: 'FF9E64' },
        { token: 'comment',    foreground: '565F89', fontStyle: 'italic' },
        { token: 'identifier', foreground: 'C0CAF5' },
        { token: 'operator',   foreground: '89DDFF' },
        { token: 'delimiter',  foreground: 'C0CAF5' },
        { token: 'type',       foreground: '7DCFFF' },
        { token: 'predefined', foreground: '7AA2F7' },
      ],
      colors: {
        'editor.background':              '#1A1B26',
        'editor.foreground':              '#C0CAF5',
        'editorLineNumber.foreground':    '#3B4261',
        'editorLineNumber.activeForeground': '#7AA2F7',
        'editor.selectionBackground':     '#283457',
        'editor.lineHighlightBackground': '#20243550',
        'editorCursor.foreground':        '#C0CAF5',
        'editor.inactiveSelectionBackground': '#28345740',
      },
    },
  },
  {
    id: 'solarized',
    label: 'Solarized',
    color: '#268BD2',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: '859900', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: '859900', fontStyle: 'bold' },
        { token: 'string',     foreground: '2AA198' },
        { token: 'string.sql', foreground: '2AA198' },
        { token: 'number',     foreground: 'D33682' },
        { token: 'comment',    foreground: '586E75', fontStyle: 'italic' },
        { token: 'identifier', foreground: '839496' },
        { token: 'operator',   foreground: 'B58900' },
        { token: 'delimiter',  foreground: '93A1A1' },
        { token: 'type',       foreground: '268BD2' },
        { token: 'predefined', foreground: '6C71C4' },
      ],
      colors: {
        'editor.background':              '#002B36',
        'editor.foreground':              '#839496',
        'editorLineNumber.foreground':    '#4E6672',
        'editorLineNumber.activeForeground': '#268BD2',
        'editor.selectionBackground':     '#073642',
        'editor.lineHighlightBackground': '#07364250',
        'editorCursor.foreground':        '#839496',
        'editor.inactiveSelectionBackground': '#07364280',
      },
    },
  },
  {
    id: 'github-dark',
    label: 'GitHub Dark',
    color: '#30363D',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: 'FF7B72', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: 'FF7B72', fontStyle: 'bold' },
        { token: 'string',     foreground: 'A5D6FF' },
        { token: 'string.sql', foreground: 'A5D6FF' },
        { token: 'number',     foreground: 'D2A8FF' },
        { token: 'comment',    foreground: '8B949E', fontStyle: 'italic' },
        { token: 'identifier', foreground: 'C9D1D9' },
        { token: 'operator',   foreground: '79C0FF' },
        { token: 'delimiter',  foreground: 'C9D1D9' },
        { token: 'type',       foreground: 'FFA657' },
        { token: 'predefined', foreground: '79C0FF' },
      ],
      colors: {
        'editor.background':              '#0D1117',
        'editor.foreground':              '#C9D1D9',
        'editorLineNumber.foreground':    '#6E7681',
        'editorLineNumber.activeForeground': '#C9D1D9',
        'editor.selectionBackground':     '#1F6FEB',
        'editor.lineHighlightBackground': '#161B22',
        'editorCursor.foreground':        '#58A6FF',
        'editor.inactiveSelectionBackground': '#1F6FEB40',
      },
    },
  },
  {
    id: 'one-dark',
    label: 'One Dark',
    color: '#282C34',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: 'C678DD', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: 'C678DD', fontStyle: 'bold' },
        { token: 'string',     foreground: '98C379' },
        { token: 'string.sql', foreground: '98C379' },
        { token: 'number',     foreground: 'D19A66' },
        { token: 'comment',    foreground: '5C6370', fontStyle: 'italic' },
        { token: 'identifier', foreground: 'ABB2BF' },
        { token: 'operator',   foreground: '56B6C2' },
        { token: 'delimiter',  foreground: 'ABB2BF' },
        { token: 'type',       foreground: 'E06C75' },
        { token: 'predefined', foreground: '61AFEF' },
      ],
      colors: {
        'editor.background':              '#282C34',
        'editor.foreground':              '#ABB2BF',
        'editorLineNumber.foreground':    '#4B5263',
        'editorLineNumber.activeForeground': '#ABB2BF',
        'editor.selectionBackground':     '#3E4451',
        'editor.lineHighlightBackground': '#2C313C',
        'editorCursor.foreground':        '#528BFF',
        'editor.inactiveSelectionBackground': '#3E445180',
      },
    },
  },
  {
    id: 'one-light',
    label: 'One Light',
    color: '#FAFAFA',
    definition: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: 'A626A4', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: 'A626A4', fontStyle: 'bold' },
        { token: 'string',     foreground: '50A14F' },
        { token: 'string.sql', foreground: '50A14F' },
        { token: 'number',     foreground: '986801' },
        { token: 'comment',    foreground: 'A0A1A7', fontStyle: 'italic' },
        { token: 'identifier', foreground: '383A42' },
        { token: 'operator',   foreground: '0184BC' },
        { token: 'delimiter',  foreground: '383A42' },
        { token: 'type',       foreground: 'E45649' },
        { token: 'predefined', foreground: '4078F2' },
      ],
      colors: {
        'editor.background':              '#FAFAFA',
        'editor.foreground':              '#383A42',
        'editorLineNumber.foreground':    '#9D9D9F',
        'editorLineNumber.activeForeground': '#383A42',
        'editor.selectionBackground':     '#E5E5E6',
        'editor.lineHighlightBackground': '#F2F2F2',
        'editorCursor.foreground':        '#526FFF',
        'editor.inactiveSelectionBackground': '#E5E5E680',
      },
    },
  },
  {
    id: 'cosmic',
    label: 'Cosmic Glow',
    color: '#6c8dfa',
    definition: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword',    foreground: '818CF8', fontStyle: 'bold' },
        { token: 'keyword.sql',foreground: '818CF8', fontStyle: 'bold' },
        { token: 'string',     foreground: '86EFAC' },
        { token: 'string.sql', foreground: '86EFAC' },
        { token: 'number',     foreground: 'FDA4AF' },
        { token: 'comment',    foreground: '4E5E87', fontStyle: 'italic' },
        { token: 'identifier', foreground: 'E2E8F0' },
        { token: 'operator',   foreground: '67E8F9' },
        { token: 'delimiter',  foreground: '94A3B8' },
        { token: 'type',       foreground: '67E8F9' },
        { token: 'predefined', foreground: 'C084FC' },
      ],
      colors: {
        'editor.background':              '#050308',
        'editor.foreground':              '#E2E8F0',
        'editorLineNumber.foreground':    '#251735',
        'editorLineNumber.activeForeground': '#6c8dfa',
        'editor.selectionBackground':     '#12174480',
        'editor.lineHighlightBackground': '#12174430',
        'editorCursor.foreground':        '#6c8dfa',
        'editor.inactiveSelectionBackground': '#12174440',
      },
    },
  },
];

export const defaultEditorThemeId = 'nvn-dark';
